### ISSUE TITLE
Editing a user's settings gives output 'This email is already taken!' when no email inputted

### ISSUE THREAD

**Issue by Wh1rr** [Fallenbagel/jellyseerr#1127] opened 2024-11-28 17:25 UTC
### Description

Currently editing a users `Display Name`, and only display name. No emails are associated with any accounts and so a blank email is 'taken'.

*If this intentional, feel free comment and close*

### Version

2.1.0

### Steps to Reproduce

> Another user without an associated email is required

# To reproduce
1. Edit a user
2. Change any value

> Toast should appear saying `This email is already taken`

### Screenshots

![toast screenshot](https://github.com/user-attachments/assets/885a1c5f-3203-4dda-be40-a1aba5a05619)

### Logs

```shell
No server-side logs available!
```

### Platform

desktop

### Device

PC - But I assume it applies to all

### Operating System

Windows 11 - But I assume it applies to all

### Browser

Firefox - But I assume it applies to all

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-11-28 17:31
Duplicate of #1094

**Closed by Fallenbagel** 2024-11-28 17:31 UTC
Labels: bug, awaiting triage
