### ISSUE TITLE
NS_ERROR_TIMEOUT trying to fetch user profile avatars from private Jellyfin

### ISSUE THREAD

**Issue by mo-st** [Fallenbagel/jellyseerr#726] opened 2024-04-21 08:15 UTC
### Description

When running jellyseerr publicly but not Jellyfin, the profile picture avatars of users don't load, as it seems they are not imported with the 'import Jellyfin Users' functionality. This may be expected, however, it leads to the page waiting and loading more than a minute trying to fetch these pictures anyway.

What I tried:
- Enabling cache (which of course doesn't work as this is only for TMDB images, I tried anyway)
- Removing internal Jellyfin URL
- Adding internal Jellyfin URL

I'm not certain if this behavior is expected, feel free to delete this report if it is. I think if possible, it would be advantageous fetching and caching the profile pictures of users on (in my case local) import, which would solve this issue.

### Version

1.8.1

### Steps to Reproduce

1. Run jellyseerr and Jellyfin in docker locally
2. Import Users from Jellyfin
3. Enable local sign-in
4. Disable New Jellyfin sign-in
5. Publish jellyseerr behind reverse proxy (enabling all necessary settings)
6. Access jellyseerr through new public URL
7. Watch request to local Jellyfin address (eg.: 1.2.3.4:8096) time out

### Screenshots

![Timeout](https://github.com/Fallenbagel/jellyseerr/assets/95215142/b71574c7-e1b9-4329-9bda-71335e316891)

### Platform

desktop

### Device

Macbook Pro

### Operating System

MacOS 14.4.1

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-04-21 17:18
Jellyfin avatars aren't imported.

It uses the internal url until external url is set.
It directly calls your avatar link. So this is a configuration issue. And a duplicate of many issues that detailed how to fix it.

If you're having trouble still, I would suggest you hop onto discord as I can provide easy to follow steps to fix this c:

**Closed** 2024-04-21 17:18 UTC
