### ISSUE TITLE
Requests are not loading

### ISSUE THREAD

**Issue by RecoX** [Fallenbagel/jellyseerr#1189] opened 2024-12-28 08:13 UTC
### Description

The requests are not working, they do not load in any browser (Firefox and Edge)

Using the latest version 2.1.0
![image](https://github.com/user-attachments/assets/a58ba063-5aa6-455e-bc9a-115c417bab61)

![image](https://github.com/user-attachments/assets/cd5151eb-8e1b-40aa-8b87-c234a13bf373)

Yesterday it was working fine, what could be ?

### Version

2.1.0

### Steps to Reproduce

It just not load

### Platform

desktop

### Database

SQLite (default)

### Device

Windows

### Operating System

Windows 10

### Browser

Edge, Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-12-28 09:26
Duplicate of #1121

**Closed by Fallenbagel** 2024-12-28 09:26 UTC
Labels: bug, awaiting triage
