### ISSUE TITLE
[Feature Request] Allow Users to Remove Shows

### ISSUE THREAD

**Issue by theianspence** [Fallenbagel/jellyseerr#487] opened 2023-09-19 20:03 UTC
### Description

Administrators are able to remove movies/shows from Radarr/Sonarr, which deletes the files from the server. 

### Desired Behavior

It would be super handy if users could have permission to delete media that they requested. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by xabufr** [comment] 2024-01-04 08:24
duplicate of #393 ?

**Comment by Fallenbagel** [comment] 2024-01-04 10:54
> duplicate of #393 ?

Yes. Thanks for pointing it out!

**Closed** 2024-01-04 10:54 UTC
