### ISSUE TITLE
[FR]: Ability to use Plex and Jellyfin OAuth at the same time

### ISSUE THREAD

**Issue by samip5** [Fallenbagel/jellyseerr#306] opened 2023-01-16 00:51 UTC
### Description

I'm frustrated when some users only have credentials over at Plex.tv and only some are on my own IdP.

### Desired Behavior

I would like to import users from both Plex and Jellyfin and allow them to login using either or.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by winnipeg21** [comment] 2023-01-26 15:16
This would cause issues. If someone has an account on jellyfin and plex and use the same user/pass it could cause an issue. Having a selector for which login is the only plausible way to go about this.

**Comment by samip5** [comment] 2023-01-26 15:53
> This would cause issues. If someone has an account on jellyfin and plex and use the same user/pass it could cause an issue. Having a selector for which login is the only plausible way to go about this.

Those should be able to be mapped if they collide or better yet, throw an error about it. 
I don't personally see that as an issue.

**Comment by winnipeg21** [comment] 2023-01-26 16:03
If you got two accounts on two different account servers with the same
password how is the software going to know which server you are trying to
use? Plex or jellyfin, now same username different passwords should be fine.

This is only if you just have one login field without a way to select which
account server you want to use.

**Comment by Fallenbagel** [comment] 2024-05-20 22:36
Duplicate of #100

**Closed** 2024-05-20 22:36 UTC
Labels: enhancement
