### ISSUE TITLE
This email is already taken!

### ISSUE THREAD

**Issue by Hammemo** [Fallenbagel/jellyseerr#1133] opened 2024-12-04 07:33 UTC
### Description

Can't save any changes to user settings due to "This email is already taken!" error message when email is blank.

### Version

2.1.0

### Steps to Reproduce

1. Go to users. 2. Select a user. 3. Edit settings. 3. Make changes or don't it makes no difference as long as email is blank. 4. Click Save Changes. 5. Receive error message saying "This email is already taken!" and changes are not saved.

### Screenshots

![Screenshot](https://github.com/user-attachments/assets/eb1fd9f5-3a78-4665-906b-ba266ba76b74)

### Platform

desktop

### Device

Dell XPS

### Operating System

Manjaro

### Browser

Firefox

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-12-04 07:43
Please do not open duplicate issues.

Duplicate of #1094 and #1127.

This issue is already fixed.

**Closed** 2024-12-04 07:43 UTC
Labels: bug, awaiting triage

**Comment by Hammemo** [comment] 2024-12-04 07:55
Issue is not fixed. You shouldn't be able to make a user at all without an email address if you require one to make any changes to it.

**Comment by Fallenbagel** [comment] 2024-12-04 08:42
> Issue is not fixed. You shouldn't be able to make a user at all without an email address if you require one to make any changes to it.

Issue is fixed. It's not released yet??
