### ISSUE TITLE
Request LDAP as backend

### ISSUE THREAD

**Issue by anschein** [Fallenbagel/jellyseerr#228] opened 2022-09-18 15:45 UTC
### Description

Currently I use LDAP server as backend for all my service,like Organizr,Emby and Nextcloud.Jellyseerr works very well with emby,but a little problem with user account.
emby login from LDAP backend,and emby didn't use email from LDAP,jellyseerr import user from emby,So I have to mannully set everyone's email for there account.
I know there is a warning when someone first login in to Jellyseerr without email setting,but they just ignore it🤣
Would be perfect if we have a LDAP support

### Desired Behavior

LDAP as backend

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2022-09-26 04:32
There is a PR for OIDC #184. That could be used with LDAP (I think?) 🤔

**Comment by anschein** [comment] 2022-09-30 11:52
> There is a PR for OIDC #184. That could be used with LDAP (I think?) 🤔

looks like just OIDC?

**Comment by EnderGamingFilms** [comment] 2023-10-25 01:39
Is this on the roadmap at all?

**Comment by ralgar** [comment] 2024-01-23 04:12
> Is this on the roadmap at all?

It's not really needed. If you use the LDAP auth plugin in Jellyfin, and use Jellyfin auth in Jellyseerr, it works just fine.

**Comment by vortex91** [comment] 2024-02-05 20:30
jellyfin doesn thave email of users when porting jellyfin users to jellyseer you have to manualy input emails.

**Comment by bilyboy785** [comment] 2024-05-25 12:30
If your users already signed in to Emby / Jellyfin, they can access Jellyseerr with their Emby / Jellyfin account, no need to connect Jellyseerr to LDAP ?

**Comment by Fallenbagel** [comment] 2024-05-25 13:36
> If your users already signed in to Emby / Jellyfin, they can access Jellyseerr with their Emby / Jellyfin account, no need to connect Jellyseerr to LDAP ?

Yup if ldap is setup, it just works by default (atleast on jellyfin. I can confirm this)

**Comment by bilyboy785** [comment] 2024-05-25 14:13
> > If your users already signed in to Emby / Jellyfin, they can access Jellyseerr with their Emby / Jellyfin account, no need to connect Jellyseerr to LDAP ?
> 
> Yup if ldap is setup, it just works by default as authentication will be handled by jellyfin which handles ldap authentication (atleast on jellyfin. I can confirm this)

I can confirm on my side for Emby, Works very Well since this new feature : 

![](https://media.cleanshot.cloud/media/15917/2Rut2KAozo38VYZBFGIG5awJBS77vi6okIB57TNs.jpeg?Expires=1716667956&Signature=ePxUt3efM3p7FgA8YmhdoYgkJUNryMXZDZyLrtNblemevd9jrtMg6bv-ck~KzwYbY60jBU4OseLUktQPBe~Yva2TTKPRTescUSSNvtbCl-8RAvUvkpPtpZeZJ27QALNJ4VuvH~jmoHeAUuruePq2GYCipFkmF4930lhDu77QScBZGYCeniEqZAdfY-TdeMlnti~ubnreBJx2wRDS1iZXgIn3YEMPS3OJC65PUCKxDzF9w5KABTfQX~n140Odt7Z0PGPIIGgK3PonDxomkIPXzsRlAZzplQibLjea1SWRl61nZ3hhIS6FqUvZLDL-QNVVOxogIM-yeJ3KAR~EFTdufg__&Key-Pair-Id=K269JMAT9ZF4GZ)

No need to import Emby users, they just need to login with their Emby account and all is ok.

**Comment by Fallenbagel** [comment] 2024-05-25 20:23
As this is possible through jellyfin/emby, I believe this feature is not really necessary for jellyseerr, therefore, I will close this issue for now.

Feel free to disagree and re-open if you think otherwise

**Comment by Fallenbagel** [comment] 2024-05-25 20:23
As this is possible through jellyfin/emby, I believe this feature is not really necessary for jellyseerr, therefore, I will close this issue for now.

Feel free to disagree and re-open if you think otherwise

**Closed** 2024-05-25 20:23 UTC
Labels: enhancement

**Comment by anschein** [comment] 2024-05-26 01:54
> As this is possible through jellyfin/emby, I believe this feature is not really necessary for jellyseerr, therefore, I will close this issue for now.
> 
> Feel free to disagree and re-open if you think otherwise

I agree with you, but in my use case, my homelab uses the same ldap backend, and using emby sync enables the user to log in successfully, but I need to tell them that they need to log in once to generate an account with emby before using jellyseerr, and I need to manually populate their email address into jellyseerr, which doesn't look so elegant

**Comment by ralgar** [comment] 2024-05-27 02:58
> using emby sync enables the user to log in successfully, but I need to tell them that they need to log in once to generate an account with emby before using jellyseerr

It doesn't work in a "pull-through" manner? This works fine with Jellyfin, the first login can be on either app.
