### ISSUE TITLE
Unable to load requests page. 

### ISSUE THREAD

**Issue by ErikHallmark** [Fallenbagel/jellyseerr#1132] opened 2024-12-04 03:18 UTC
### Description

When I go to the requests page in my Jellyseer instance, the page hangs and the page title just becomes ```{IP ADDRESS}/requests```

### Version

2.1.0

### Steps to Reproduce

1. Open jellyseerr
2. navigate to the "requests" page via the sidebar
3. page fails to load. 

### Screenshots

![Screenshot_20241203_191514](https://github.com/user-attachments/assets/b778bd63-7f21-4b27-84dd-d63335a3131b)

### Logs

```shell
(No logs relevant to the issue in either jellyfin logs or browser console)
```

### Platform

desktop

### Device

Thinkpad X1 Yoga, Pixel 7 pro

### Operating System

Manjaro linux, android

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-12-04 04:10
Duplicate of #1121

**Closed by Fallenbagel** 2024-12-04 04:10 UTC
Labels: bug, awaiting triage
