### ISSUE TITLE
Notification per season

### ISSUE THREAD

**Issue by BreizhHardware** [Fallenbagel/jellyseerr#423] opened 2023-07-10 09:18 UTC
### Description

When someone request only a season or two of a series that has more than one season, the media availability notifications (over discord or telegram) will not be send even if the requested season is available.

### Version

1.5.0

### Steps to Reproduce

Request only one season of a series
Wait for the download and discover to be done

### Platform

desktop

### Device

Dell T320

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2023-11-07 14:09
I dont understand. I have requested many times only one season of a multiple season show and I got the available notification after it was completed and available.

(Heres fullhouse. 8 seasons. Requested only 1 season. Available notification)
![Screenshot_20231107_190652_Telegram](https://github.com/Fallenbagel/jellyseerr/assets/98979876/89f23ac2-03a2-4006-9986-5b2de2f310d7)

(Here's another example. For context, the addams family has 2 seasons)

![Screenshot_20231107_190545_Telegram](https://github.com/Fallenbagel/jellyseerr/assets/98979876/9600a9fe-67ee-4051-a320-de3feafb007d)

**Comment by BreizhHardware** [comment] 2023-11-08 21:14
As you can see on this image, I don't have any notification after a request and a download of (in this case Stranger Things)
![image](https://github.com/Fallenbagel/jellyseerr/assets/72651575/b0f3e081-58a7-4e9f-9ce4-3647e5988683)

**Comment by BreizhHardware** [comment] 2023-11-08 21:15
If you need I can go in a discord or somthing like this to talk faster

**Comment by Fallenbagel** [comment] 2023-11-08 21:30
> As you can see on this image, I don't have any notification after a request and a download of (in this case Stranger Things)
> ![image](https://github.com/Fallenbagel/jellyseerr/assets/72651575/b0f3e081-58a7-4e9f-9ce4-3647e5988683)
> 

Given that stranger things doesn't even have a status badge, that indicates that that request itself is fucked. It could also be your instance is fucked

**Comment by nevrending** [comment] 2023-12-17 07:51
Hi, I'm experiencing a similar thing.

![Screenshot 2023-11-12 at 16 34 24](https://github.com/Fallenbagel/jellyseerr/assets/4745298/22bb81c8-4f10-4f43-8062-382ddcd0d251)

All episodes of Season 1 is fully Available, but the request stays in Partially Available.

![Screenshot 2023-11-12 at 16 34 37](https://github.com/Fallenbagel/jellyseerr/assets/4745298/90c2565e-5c86-494c-b56a-5e4c5cf17692)

Is this an intended behaviour?

**Comment by Fallenbagel** [comment] 2023-12-17 08:29
That request tab status is for OVERALL SHOW status. Inside you're seeing season status. Your overall show status would be partial because season 2 is partial.

**Comment by nevrending** [comment] 2023-12-18 05:10
@Fallenbagel I see, thanks for the explanation. I thought it's the status of the request (i.e status of requested season), hence I thought when the requested season is fully available, the status of/on the request will change to Available.

**Comment by Fallenbagel** [comment] 2024-02-09 16:34
> Hello, by switching the last week my docker container to the dev branch I have no issue now.

Oh yeah this has been fixed. I forgot to close the issue. Thanks!

**Closed** 2024-02-09 16:35 UTC
Labels: bug
