### ISSUE TITLE
Add ability to request just the pilot (first) episode of a series

### ISSUE THREAD

**Issue by zacps** [Fallenbagel/jellyseerr#502] opened 2023-10-16 09:19 UTC
### Description

Sometimes I want to try out a series by watching just the first episode, currently I need to request the whole first season to do this.

### Desired Behavior

As title

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by tippfehlr** [comment] 2024-01-11 15:41
Duplicate of #264. See https://github.com/Fallenbagel/jellyseerr/issues/592#issuecomment-1847836482 why this might take a while.

**Comment by Fallenbagel** [comment] 2024-01-11 19:24
Thank you @tippfehlr 
Closing this because duplicate

**Closed by Fallenbagel** 2024-01-11 19:24 UTC
