### ISSUE TITLE
Something went wrong retrieving movie {"errorMessage":"Cannot read properties of undefined (reading 'cast')","movieId":"1246"}

### ISSUE THREAD

**Issue by kristianvmd** [Fallenbagel/jellyseerr#1122] opened 2024-11-24 16:14 UTC
### Description

Submit this movie for error reporting: https://www.themoviedb.org/movie/1246-rocky-balboa

### Version

2.1.0

### Steps to Reproduce

none

### Logs

```shell
2024-11-24T15:50:51.967Z [debug][API]: Something went wrong retrieving movie {"errorMessage":"Cannot read properties of undefined (reading 'cast')","movieId":"1246"}
```

### Platform

desktop

### Device

x86

### Operating System

windows

### Browser

chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-11-24 16:32
This is not a bug with jellyseerr but a bug with tmdb api. Should be fixed when your tmdb api 

![Screenshot_20241125_003202_Chrome Dev.jpg](https://github.com/user-attachments/assets/a8b3a14f-7577-471a-9677-cdaff7385653)

**Closed** 2024-11-24 16:32 UTC
Labels: bug, awaiting triage
