### ISSUE TITLE
Filter for Date Select not rendering correctly

### ISSUE THREAD

**Issue by solomon-b** [Fallenbagel/jellyseerr#606] opened 2024-01-01 03:56 UTC
### Description

The Date Filter widget is not rendering correctly.

### Version

1.7.0

### Steps to Reproduce

This occurs every time I use the Date filter.

### Screenshots

![2023-12-31:19:53:1704081239](https://github.com/Fallenbagel/jellyseerr/assets/24038/e936f0f1-b303-48cf-911a-78de89e673d4)

### Platform

desktop

### Device

Dell XPS 13

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-01-01 11:53
This is already fixed and a duplicate of #415

**Closed by Fallenbagel** 2024-01-01 11:53 UTC

**Comment by solomon-b** [comment] 2024-05-18 18:39
I'm still getting this issue with 1.8.1

**Comment by Fallenbagel** [comment] 2024-05-18 20:45
> I'm still getting this issue with 1.8.1 with both firefox and chrome.

What is your install method?

**Comment by solomon-b** [comment] 2024-05-18 22:38
> > I'm still getting this issue with 1.8.1 with both firefox and chrome.
> 
> What is your install method?
> 
> I checked docker and baremetal and both seems to not have this issue at all

With nixos which does a 'baremetal' installation with `yarn`: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/servers/jellyseerr/default.nix#L57-L73

**Comment by Fallenbagel** [comment] 2024-05-19 00:11
> With nixos which does a 'baremetal' installation with `yarn`: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/servers/jellyseerr/default.nix#L57-L73

Ah yes. I thought so. I am also on nixos with nixpkg. And yes this is an issue on it. Unfortunately this seems to be related to how nixpkg builds it. The issue on jellyseerr side is fixed.

**Comment by solomon-b** [comment] 2024-05-21 15:21
> > With nixos which does a 'baremetal' installation with `yarn`: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/servers/jellyseerr/default.nix#L57-L73
> 
> Ah yes. I thought so. I am also on nixos with nixpkg. And yes this is an issue on it. Unfortunately this seems to be related to how nix derivation builds it. The issue on jellyseerr side is fixed.

Thank you, I ran it using the docker file and confirmed that the issue is with the nixos distribution.
