### ISSUE TITLE
Lost admin settings and incomplete profile warning

### ISSUE THREAD

**Issue by apolatynski** [Fallenbagel/jellyseerr#363] opened 2023-03-29 08:16 UTC
### Description

Installed Jellyseerr using a Jellyfin user account (no other users are added to Jellyseerr)

At first everything seemed to be working fine. Had access to admin settings, set email address and email notifications.

After a while I noticed that I no longer see the Settings section on the main screen, and there is a warning "Profile is incomplete. An email address is required". Profile page allows to type in the email, but trying to save it always fails with "Something went wrong while saving settings". Int the logs only the warning about no valid email address appears. Logging out and back in doesn't solve the problem.

Surprisingly, when requesting new movie. Email notifications do work.

### Version

1.4.1

### Steps to Reproduce

1. Run Jellyseerr in docker container
2. Go through the setup using admin user from Jellyfin
3. Setup email for the user and email notifications
4. ?
5. Notice the user can login using Jellyfin credentials, but no longer has admin privileges
6. Jellyfin reports incomplete profile and doesn't allow to add email

### Logs

```shell
2023-03-29T07:56:01.261Z [warn]: User  has no valid email address
```

### Platform

desktop

### Device

PC

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Callum027** [comment] 2023-08-25 13:41
I am also experiencing this issue with the same version of Jellyseerr, with the following logs. Nothing else particularly useful is logged even with the log level set to `debug`.

```
jellyseerr  | 2023-08-25T13:37:17.128Z [warn]: User null has no valid email address 
jellyseerr  | 2023-08-25T13:37:23.274Z [warn]: User  has no valid email address
```

**Comment by Fallenbagel** [comment] 2023-08-25 15:13
Your version is outdated. And the email address appears because you have ticked the email notification `require user email`.

Just go to the profile and you can update the email there too. Or hop onto discord and I'll help you it's easier to follow there.

**Comment by Callum027** [comment] 2023-08-25 21:05
Hi there, thanks for the quick reply. I just updated to 1.6.0 and was able to reproduce the issue.

I created a post in the support channel regarding this issue. Thanks in advance!

https://discordapp.com/channels/952656177924300932/1144736645216743584/1144736645216743584

**Comment by Callum027** [comment] 2023-08-25 22:32
We were able to figure out the cause of the issue on my end.

I first tried creating a local user to see how that would react. I was able to set *an* email address when creating (and later changing) the user, but the email address I was using when I got the error gave me an actual error message this time. Telling me that my email address was **already in use** by another user!

So the admin Jellyfin user that I initialised the Jellyseerr instance with, and the regular Jellyfin user I use day-to-day are different. However, when I was trying to change the email address on my regular user, I was using the same email address I had configured my Jellyseerr admin user with.

Changing the two users so that the emails are different resolved the issue.

Jellyseerr doesn't appear to handle the error case where you try to set an email address to a Jellyfin user that is already assigned to another user properly, resulting in a `500 Internal Server Error` when you try to make the request. @Fallenbagel will create a separate issue for this.

Thanks for the help!

**Closed** 2023-11-06 22:02 UTC
