### ISSUE TITLE
Animation type support. (with a side of Anime support for movies)

### ISSUE THREAD

**Issue by devanteweary** [Fallenbagel/jellyseerr#1063] opened 2024-11-01 00:24 UTC
### Description

What I'm requesting is Jellyseerr to support a separate Type for both movies and series. 

Much like the Series service supports Anime as its own thing (which I appreciate and love), I'd love if we can get Animation as well in both movies and series.

And related, can we also add Anime as a movie type?

### Desired Behavior

When adding Radarr, have an additional Animation and Anime type much like Sonarr already has an Anime type.  
Same thing in Sonarr.

### Additional Context

For people like me who separate live action, animated (non-anime movies), and anime media, this would be tremendously helpful. 
As it stands now, I have to manually move anime movies into my `Movies - Anime` library and all animated movies and series into their respective `Movies or Series - Animated`.

Thank you!

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-11-01 06:27
Duplicate of #360

**Closed by Fallenbagel** 2024-11-01 06:27 UTC
Labels: enhancement, awaiting triage

**Comment by devanteweary** [comment] 2024-11-01 21:43
> Duplicate of #360

Hey @Fallenbagel , looks like that ticket is just wanting anime in movies.

Mine is about Animation (non-anime - like Lion King or Duck Tales) in both Movies and Series.

**Comment by Fallenbagel** [comment] 2024-11-02 00:43
> > Duplicate of #360
> 
> Hey @Fallenbagel , looks like that ticket is just wanting anime in movies.
> 
> Mine is about Animation (non-anime - like Lion King or Duck Tales) in both Movies and Series.

Okay but this essentially achieves what you want as well
#967

**Comment by devanteweary** [comment] 2024-11-15 19:14
> > > Duplicate of #360
> > 
> > 
> > Hey @Fallenbagel , looks like that ticket is just wanting anime in movies.
> > Mine is about Animation (non-anime - like Lion King or Duck Tales) in both Movies and Series.
> 
> Okay but this essentially achieves what you want as well #945

Sorry to late reply but yes, that actually is even better than my request!
