### ISSUE TITLE
Show available episodes of a TV Show, not only Seasons

### ISSUE THREAD

**Issue by ChristophCaina** [Fallenbagel/jellyseerr#894] opened 2024-07-25 23:58 UTC
### Description

It would be great, if there could be an indicator on the Episode-Level of a TV show, which Episodes are available, and which one are missing.
For missing Episodes, you could then also try to create a request... :)

In this example, it's not visible, which episodes are missing for Season3 & 4 ...
![grafik](https://github.com/user-attachments/assets/2c9700ec-368f-4e27-828c-55464548aee3)

### Desired Behavior

There should be an indicator on the Episode-Level to indicate, which episodes are available and which are maybe missing.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-07-26 11:26
Part of and duplicate of #264

**Closed by Fallenbagel** 2024-07-26 11:26 UTC
