### ISSUE TITLE
[Feature Request] Sync User request permissions to library access (4K)

### ISSUE THREAD

**Issue by mLgz0rn** [Fallenbagel/jellyseerr#510] opened 2023-10-22 18:51 UTC
### Description

No

### Desired Behavior

Hello.
So I don't know if this has been requested yet.

But I would like to see as with Radarr and Sonarr has a default and default 4K option, also adding this to the Library section.
And if users within Jellyfin has access to these libraries they will automatically get access to requesting content that are not 4k and 4K in jellyseerr depending on their access to libraries in jellyfin.
And then maybe creating a sync users task, so if their access to libraries is changed in jellyfin this will also change in jellyseerr

Don't know if this makes sense or if this is even possible.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-05-23 11:47
Duplicate of #180

**Closed by Fallenbagel** 2024-05-23 11:47 UTC
