### ISSUE TITLE
Request Future Shows Only

### ISSUE THREAD

**Issue by bjhille** [Fallenbagel/jellyseerr#622] opened 2024-01-13 22:41 UTC
### Description

When requesting a series, you can request certain seasons and then Sonarr will get those seasons and continue to look for new episodes.  It would be cool if an option was added to only check for new episodes going forward.  In other words, if I've already seen half of a season on normal TV (ie. cable or over-the-air) I don't need to get the shows I've already seen, just need to get shows going forward.

### Desired Behavior

Don't want to download shows that have already aired, just need to get Sonarr to get new episodes going forward from the requested date.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-01-13 22:55
Duplicate of #332

**Closed** 2024-01-13 22:56 UTC
