### ISSUE TITLE
Block media from certain streaming services (netflix,amazon,etc)

### ISSUE THREAD

**Issue by gaming09** [Fallenbagel/jellyseerr#300] opened 2023-01-12 19:30 UTC
### Description

It would be great to be able to block content that is on certain streaming services IE Netflix or prime, paramount. Services that i know all my users have 

### Desired Behavior

Either don't show it to begin with or have a popup that says "Admin has blocked downloads from <servicename> , please watch <showname> or <moviename>  on <servicename>"

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2023-01-12 21:15
Like hide them from being discoverable too?

**Comment by winnipeg21** [comment] 2023-01-26 15:14
This be a very great idea, but don't hide the media outright. Just have a banner over the request button saying "This content is already on X site"

**Comment by Fallenbagel** [comment] 2023-01-26 18:24
>  Just have a banner over the request button saying "This content is already on X site"

It currently does show where it is currently streaming at on jellyseerr itself

![Screenshot_20230126_232223_Chrome Dev.jpg](https://user-images.githubusercontent.com/98979876/214918606-5192e2ac-6813-4d3f-ad9c-f8c0b79f65bf.jpg)

**Comment by laborantine** [comment] 2023-05-01 21:12
(sorry for my english, i'm french)

+1 for this feature.

Already having an account at Prime Video, Netflix and Disney+ that I share with my family, some users may not care that the content they want is already on a platform that we pay for. It's duplicate, it "pollutes" our storage space and we therefore pay a service for nothing. A customizable message that will redirect the user to a Netflix link, for example, would be a plus. If he gives the link to the Netflix series/movie he wants would be even better.

Jellyseerr is a great tool, I'm impressed with your work, keep it up!

**Comment by Fallenbagel** [comment] 2024-05-23 11:27
Duplicate of #206

**Closed** 2024-05-23 11:28 UTC
