### ISSUE TITLE
[Feature] Ability to hide undesirable suggestions in Discover, Movies or Series page

### ISSUE THREAD

**Issue by sunnyd24** [Fallenbagel/jellyseerr#1005] opened 2024-10-13 09:30 UTC
### Description

I always find that there are many Shows or Movies that I do not want to see on the Discover, Movies or Series home pages.

Therefore, I have to regularly scroll past these items before I get to see content I do want to see more of. This would make the content more relevant for the user. 

### Desired Behavior

Is there a way to long select on an item/poster and hide from suggestions that will persist across sessions?

Maybe these hidden items can be stored in somewhere like a database to remove from suggestions. 
Also, a way to restore these items would be useful, in the case of accidental hides. 

### Additional Context

I believe the suggestions are currently provided and sorted by the provider like TMDB, so server side filtering in Jellyseerr would be required to hide items in list. 

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by JSouthGB** [comment] 2024-10-13 18:52
Possible dupe of #970 (?)

#632 is in the develop branch currently. I haven't tested it myself.

**Comment by Fallenbagel** [comment] 2024-10-13 19:16
Duplicate of #970

**Closed by Fallenbagel** 2024-10-13 19:16 UTC
Labels: enhancement, awaiting triage
