### ISSUE TITLE
Ability to change the "DB" that jellyseer uses eg. TVDB

### ISSUE THREAD

**Issue by jarrydstan** [Fallenbagel/jellyseerr#671] opened 2024-02-27 23:45 UTC
### Description

Theres some issues with some series - for example The Haunting of Bly Manor. It is querying the movie db instead of TVDB which Sonarr uses, and won't download the correct videos for the series, which instead gets Haunting of Hill House. TVDB sees "The Haunting" as a series, and "Season 1" is Hill house and "Season 2" is Bly Manor. This can be worked around by manually downloading the required series, but obviously a bit painful!

### Desired Behavior

Either in the server, or on the front end, provide option to override the metadata provider either for the invidual series or "TV Shows" in general.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-02-28 03:46
Not possible. Tvdb is paid. And also sort of duplicate of #465

**Closed** 2024-02-28 03:47 UTC
