### ISSUE TITLE
A recently added newsletter

### ISSUE THREAD

**Issue by PartyingChair** [Fallenbagel/jellyseerr#1188] opened 2024-12-28 03:22 UTC
### Description

I used to use Tautulli for a recently added email once per week, but having moved to Emby from Plex, I find Emby's built in newsletter extremely lacking. Just a text list of what's been added, no images or info beyond that. It also seems mildly unreliable. Ombi has an actually good newsletter in my opinion, but it's also worse in basically every other way in my opinion. 

### Desired Behavior

A setting where I could send a newsletter just listing what's new, once per week, (or possibly configurable) that sends selected users a list of what's new on the server.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by devanteweary** [comment] 2024-12-30 07:14
I've been looking for a way to send weekly newsletters on what's coming up this week.

Maybe something like "Requests that are getting digital releases this week." as well as popular movies in a different section.  
Something like that.

Haven't found anything yet.

**Comment by gauthier-th** [comment] 2024-12-30 14:02
Duplicate of #167 and #330

**Closed by gauthier-th** 2024-12-30 14:02 UTC
Labels: enhancement, awaiting triage
