### ISSUE TITLE
[Feature Request] Implement per-user option for default Radarr/Sonarr services

### ISSUE THREAD

**Issue by joel35** [Fallenbagel/jellyseerr#777] opened 2024-05-27 14:50 UTC
### Description

I have separate TV / Movie libraries in Jellyfin for kids / adults which use different root directories. In Jellyseerr I'd like different users to use specific root directories automatically.

This could be achieved by setting up "Radarr" and "Radarr Kids" services which point to the correct root directory.

<img width="779" alt="Screenshot 2024-05-27 at 3 40 32 PM" src="https://github.com/Fallenbagel/jellyseerr/assets/64959969/1a80759b-f350-4b81-b015-639f670d0b9a">

However, it only seems possible to set a global default service, rather than per-user.

### Desired Behavior

In the user settings, add the option of assigning a specific default service to them rather than just the global default.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-05-28 10:55
Duplicate of #599

**Closed by Fallenbagel** 2024-05-28 10:55 UTC
