### ISSUE TITLE
Cannot connect to Emby

### ISSUE THREAD

**Issue by PartyingChair** [Fallenbagel/jellyseerr#1187] opened 2024-12-27 23:17 UTC
### Description

In initial setup, sometimes it won't even let me get past step 2: "Sign in to your account" with an Emby, and once I get past that and to step 3: "Configure Media Server" no matter what I do, it will NOT sync my libraries. It'll either give some random error, or it'll load forever. The logs seem to think it's trying to connect to Jellyfin, despite UI showing Emby and me selecting Emby.

### Version

Can't even get to settings to check version

### Steps to Reproduce

1. Start jellyseerr from scratch
2. Follow steps to set up an Emby server
3. Try to sync library

### Screenshots

![image](https://github.com/user-attachments/assets/45298714-3ec1-4d16-9f4d-d5ab8b1ed0c9)

### Logs

```shell
2024-12-27T23:06:11.451Z [info]: Commit Tag: $GIT_SHA 
2024-12-27T23:06:11.804Z [info]: Starting Overseerr version 2.1.0 
2024-12-27T23:06:12.138Z [info][Notifications]: Registered notification agents 
2024-12-27T23:06:12.172Z [info][Jobs]: Scheduled jobs loaded 
2024-12-27T23:06:12.235Z [info][Server]: Server ready on port 5055 
2024-12-27T23:07:42.706Z [info][API]: Sign-in attempt from Jellyfin user with access to the media server; editing admin user for Jellyseerr {"ip":"::ffff:10.52.3.47","jellyfinUsername":"Admin"}
2024-12-27T23:07:42.716Z [error][Jellyfin API]: Something went wrong while creating an API key from the Jellyfin server {"error":"Forbidden"}
2024-12-27T23:07:42.716Z [error][Auth]:
```

### Platform

desktop

### Database

None

### Device

Macbook Air

### Operating System

MacOS 15.2

### Browser

Safari, Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-12-27 23:39
Add the api key manually? It says there on the error log "forbidden" so it wasn't able to automatically grab an api key because emby kept refusing.

This is not a bug but a support issue and as such should be moved to discord.

**Comment by PartyingChair** [comment] 2024-12-27 23:46
It's absolutely a bug, as I can't add API key manually - it straight up doesn't let me. When I try to, the save button becomes greyed out and I can't click it.

**Comment by Fallenbagel** [comment] 2024-12-27 23:48
> It's absolutely a bug, as I can't add API key manually - it straight up doesn't let me. When I try to, the save button becomes greyed out and I can't click it. 

Can you show me a screenshot? I would still suggest you hop onto discord to debug this. We can't fix something we cannot reproduce and debugging will help with that.

**Comment by Fallenbagel** [comment] 2024-12-27 23:48
> It's absolutely a bug, as I can't add API key manually - it straight up doesn't let me. When I try to, the save button becomes greyed out and I can't click it. 

Can you show me a screenshot? I would still suggest you hop onto discord to debug this. We can't fix something we cannot reproduce and debugging will help with that.

**Comment by PartyingChair** [comment] 2024-12-27 23:50
<img width="859" alt="Untitled" src="https://github.com/user-attachments/assets/e1b5b998-553b-4b64-b3c6-643c3194b703" />

**Comment by PartyingChair** [comment] 2024-12-27 23:50
Obviously when I really try it, the external Url is real, but it won't let me save changes no matter what

**Comment by Fallenbagel** [comment] 2024-12-27 23:59
@PartyingChair could you confirm if the same thing happens on develop? There was an emby issue that was fixed in develop

**Comment by PartyingChair** [comment] 2024-12-28 00:06
Deleted container, deleted appdata. Reinstalled from scratch on develop. Exact same issue.

**Comment by Fallenbagel** [comment] 2024-12-28 00:07
![image](https://github.com/user-attachments/assets/684e9659-7a1d-41c1-b1c2-59838dc76681)

I cant replicate this. I am able to save as you can see from my screenshot.

**Comment by Fallenbagel** [comment] 2024-12-28 00:10
@PartyingChair Can you check when you go to this step page whether the settings.json is populated with your server details?

**Comment by PartyingChair** [comment] 2024-12-28 00:14
I don't know what to tell you. I can't. Not sure why, or what would be different. Image is fallenbagel/jellyseerr:develop
<img width="1678" alt="Untitled" src="https://github.com/user-attachments/assets/d00f7ae9-01b2-4c4d-b1db-72294eddea69" />

Attached settings.json (I redacted some stuff that looked like it might be private keys, let me know if you need something I may have redacted accidentally)
[settings.json](https://github.com/user-attachments/files/18264427/settings.json)

**Comment by Fallenbagel** [comment] 2024-12-28 00:17
@PartyingChair Your settings.json did not save any values from step 2. I think Jellyseerr is unable to write to it perhaps. Your jellyfin block (ignore the naming doesnt matter if youre on emby or jellyfin it will save to that block) is empty. It has to have your details like serverid. Meaning it did not save during your login step. Usually due to permission issues but this is 99% a configuration issue and not a bug and I would strongly advice to help us troubleshoot by hopping onto discord.

**Closed by Fallenbagel** 2024-12-28 00:17 UTC
Labels: support, more information needed

**Comment by PartyingChair** [comment] 2024-12-28 00:20
I’m going to still disagree with you. If it was a config/permissions issue, I wouldn’t be able to connect it to plex. I can. Works flawlessly.

**Comment by Fallenbagel** [comment] 2024-12-28 00:23
> I’m going to still disagree with you. If it was a config/permissions issue, I wouldn’t be able to connect it to plex. I can. Works flawlessly.

Then I am going to still disagree with you as well as there are several users using jellyseerr on EMBY. If you are unwilling to help us troubleshoot, we cannot help you.

**Comment by PartyingChair** [comment] 2024-12-28 00:27
Sorry. I’ll just change the permission that says “save everything plex related, but nothing Emby related.” Where would I find that setting?


I’ve provided everything you’ve asked for, and now you’re telling me in not going to help you help me? Come on dude.

**Comment by Fallenbagel** [comment] 2024-12-28 00:32
> I’ve provided everything you’ve asked for, and now you’re telling me in not going to help you help me? Come on dude.

I have stated several times, to help us help you by hopping onto discord to debug. We cannot fix something we or none of the other SEVERAL emby users cannot reproduce. We are all humans. Not psychics to be able to guess your exact issue without troubleshooting. 

I have mentioned several times to hop onto discord so we can do some real-time debugging there. WHAT you provided is insufficient enough that we need real-time debugging. Enlighten me how SEVERAL OTHER EMBY users are perfectly using jellyseerr if this is specific to emby??
