### ISSUE TITLE
Language Notifications?

### ISSUE THREAD

**Issue by FritLP** [Fallenbagel/jellyseerr#872] opened 2024-07-12 07:22 UTC
### Description

I have activated the notifications via Slack on Jellyseerr. Unfortunately, these are apparently only available in English. Now I wanted to ask whether it is possible to change this language somehow or to edit the files myself?

### Desired Behavior

Is it possible to change it after all? Would otherwise be a nice feature. Or can you edit the files yourself for the language?

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-07-12 09:13
Duplicate of #335

**Closed** 2024-07-12 09:14 UTC
