### ISSUE TITLE
Monitoring of future episodes

### ISSUE THREAD

**Issue by pafade89** [Fallenbagel/jellyseerr#1019] opened 2024-10-17 11:51 UTC
### Description

Unfortunately its not possible to request the monitoring of future episodes.

### Desired Behavior

It would be a very good feature for tv shows, if we would be able to request future monitoring in Sonarr without requesting the old ones.

An idea is to get an extra slider for future episodes after the last released season.

![image](https://github.com/user-attachments/assets/9179df09-2ae1-4340-ab64-f1651629ef62)

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment] 2024-12-19 14:49
Duplicate of #1019

**Closed by gauthier-th** 2024-12-19 14:49 UTC
Labels: enhancement, awaiting triage

**Comment by pafade89** [comment] 2024-12-19 14:56
@gauthier-th the duplicate is the same issu :P

Please reopen.

**Comment by Fallenbagel** [comment] 2024-12-19 14:56
> Duplicate of #1019

Huh?

**Comment by gauthier-th** [comment] 2024-12-19 14:58
Sorry, I meant #325

**Comment by pafade89** [comment] 2024-12-19 15:00
> Sorry, I meant #325 

👍
