### ISSUE TITLE
Play on Jellyfin

### ISSUE THREAD

**Issue by coromjones97** [Fallenbagel/jellyseerr#625] opened 2024-01-16 18:45 UTC
### Description

I have a user that doesn't have access in Jellyfin to a certain library of movies. Jellyseerr shows that it is already in Jellyfin and then "Play on Jellyfin" is selected in Jellyseerr, the movie opens in Jellyfin, even if the user has no access in Jellyfin settings to that movie.

### Version

10.8.13

### Steps to Reproduce

1 - Make Jellyfin user without permission to Library 1.
2 - Have movie in Jellyfin in Library 1.
3 - Open Jellyseerr and search for same movie.
4 - Click "Play on Jellyfin"

### Platform

tablet

### Device

Lenovo Tab 4

### Operating System

Android

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-01-16 20:59
Limitation with jellyfin that does not block but only hides items when access is restricted. Also duplicate of #180

**Closed by Fallenbagel** 2024-01-16 21:00 UTC
