### ISSUE TITLE
Add Support for Music and Book Requests

### ISSUE THREAD

**Issue by Shivan281** [Fallenbagel/jellyseerr#955] opened 2024-09-01 15:59 UTC
### Description

I would like to request the addition of support for music and book requests in Jellyseerr. This feature would allow users to request albums, songs, and books in addition to movies and TV shows. It would enhance the versatility of Jellyseerr and make it a more comprehensive media request management tool.

Benefits:

Expands the types of media that can be requested.
Provides a unified platform for managing all media requests.
Increases user satisfaction by catering to a wider range of interests.
Implementation:

Integrate with music and book databases (e.g., MusicBrainz, Goodreads).
Add new request forms for music and books.
Update the UI to accommodate the new media types.

### Desired Behavior

I would like to request the addition of support for music and book requests in Jellyseerr. This feature would allow users to request albums, songs, and books in addition to movies and TV shows. It would enhance the versatility of Jellyseerr and make it a more comprehensive media request management tool.

Benefits:

Expands the types of media that can be requested.
Provides a unified platform for managing all media requests.
Increases user satisfaction by catering to a wider range of interests.
Implementation:

Integrate with music and book databases (e.g., MusicBrainz, Goodreads).
Add new request forms for music and books.
Update the UI to accommodate the new media types.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment] 2024-09-01 16:14
Duplicate of #96 and #134

**Closed by gauthier-th** 2024-09-01 16:14 UTC
