### ISSUE TITLE
Allow hiding /showing blacklisted items even for users allowed to manage and to view blacklisted items

### ISSUE THREAD

**Issue by nupulu** [Fallenbagel/jellyseerr#1040] opened 2024-10-21 15:03 UTC
### Description

My use case for the blacklisted items is to mark media as considered to not-to-be-requested. Once an item has been considered I would like it to be hidden because I wouldn't want to consider it again and o clean up the view, which speeds up the consideration process. The "blacklisted" icon is nice, but easy overlooked.

### Desired Behavior

For users who have permission to view blacklisted items there should be an option that allows showing/hiding blacklisted items also in their UI view (not just for users not allowed to view blacklisted items)

### Additional Context

A simpler, yet acceptable version of this would be not to show/hide blacklisted items, but to always show blacklisted items to users who have viewing permission, but to render blacklisted items with significantly lower brightness so that it is instantly visually clear that these items are blacklisted.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment] 2024-10-21 15:14
Duplicate of #1022

**Closed** 2024-10-21 15:15 UTC
Labels: enhancement, awaiting triage
