### ISSUE TITLE
Support for single URL fields for Radarr/Sonarr

### ISSUE THREAD

**Issue by sdfg2** [Fallenbagel/jellyseerr#250] opened 2022-10-31 18:13 UTC
### Description

My Radarr and Sonarr sit behind a reverse proxy.  When adding to Jellyseerr there's no option to add the URL.  I can press SSL, I can put in port 443, but when I put in 'domain.tld/radarr' Jellyseerr complains.

### Desired Behavior

There should be a standard URL input, not separated with an SSL toggle and port input box.  Then the URLS "http://127.0.0.1:7878", "https://127.0.0.1:7878", "http://hostname:7878", "https://hostname:7878", "http://domain.tld/radarr", and "https://domain.tld/radarr" all work with a single input box.

### Additional Context

I realise this might be from Overseerr but, either way it's something that needs fixed.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2022-10-31 18:45
A lot of people use 443 w the url on url field w ssl or ssl off. Is it not working? 🤔 (ik not a solution but just curious why uts not working)

**Comment by sdfg2** [comment] 2022-10-31 19:26
![image](https://user-images.githubusercontent.com/5736478/199092874-3febbec4-3b9c-4e14-87ba-914a0dc4402d.png)

**Comment by Fallenbagel** [comment] 2022-10-31 19:33
> ![image](https://user-images.githubusercontent.com/5736478/199092874-3febbec4-3b9c-4e14-87ba-914a0dc4402d.png)

I think the problem is basepath is not accepted. I'll have a look

**Comment by sdfg2** [comment] 2022-10-31 20:57
Yes I see now, but this really has no need to be this complicated.  All this information is held in a URL anyway.

**Comment by Fallenbagel** [comment] 2022-10-31 22:38
> Yes I see now, but this really has no need to be this complicated. All this information is held in a URL anyway.

As the current implementation is from overseerr, we did not catch that it did not support radarr/sonarr basepaths. Should be a simple feature to implement (and maybe PR upstream)

**Comment by Fallenbagel** [comment] 2022-10-31 22:52
@sdfg2 Wait. I just figured it out. I did not see this before but there is support for it.

![image](https://user-images.githubusercontent.com/98979876/199124747-1a30df39-b5de-4b5c-914d-fac2a84f46a2.png)

There is a field to add the base path of radarr and sonarr on each

**Comment by sdfg2** [comment] 2022-11-03 10:57
Yeah, as I said I spotted that.  My point is that there is no need for 4 inputs for this information - it is all contained with a *single* URL.

**Comment by Fallenbagel** [comment] 2022-11-03 13:07
It does make sense tho. Because currently one of the issues we are facing on jellyseerr is the trailing slash. 
We merged a commit recently to fix trailing slash from being added by treating the field as a url, but it ended up breaking basepaths. The way sonarr/radarr is handled kind of fixes that problem

**Closed** 2022-12-17 00:39 UTC
