### ISSUE TITLE
Plex configuration does nothing

### ISSUE THREAD

**Issue by jazzgott** [Fallenbagel/jellyseerr#34] opened 2022-03-29 04:29 UTC
#### Description

As in the title; settings -> plex doesn't do anything. The local plex server does not get detected, and when trying to add manually it fails to connect and says "Authentication failed, reason: undefined", probably because of the other bug - the one where plex login doesn't work.

#### Version

develop-

#### Steps to Reproduce

1. Go to settings
2. Click on Plex
3. Try using the two arrow button to refresh plex servers
4. Nothing happens
5. try to add IP manually
6. Click save changes
7. You get an error saying Unable to connect to Plex! (see screenshot)

#### Expected Behavior

I expected the server to be found, than to be asked credentials and then to be able to scan my plex server contents.

#### Screenshot
![Zrzut ekranu 2022-03-29 052501](https://user-images.githubusercontent.com/29210679/160533350-73e000e9-9f05-476c-bd9e-7051d916f074.jpg)

#### Device

- Windows 11 PC
- Firefox AND Edge

**Comment by Fallenbagel** [comment] 2022-03-29 19:06
This is with the latest tag right? Yeah currently jellyseerr doesn't work with plex, however the develop version does (although there is one issue we are facing on it but hopefully will be fixed soon).

As for the reason why plex doesn't work, jellyseerr was intended to give support for jellyfin (an now emby) in addition to plex, however only one media server can be used at a time. That was the original plan but somehow we messed up the plex database query, which we are trying to fix for the next version so only jellyfin/emby works.

We humbly apologise for the inconvenience and might I suggest using overseerr for plex integration because it has full plex support with new features(that we haven't yet established).

**Comment by jazzgott** [comment] 2022-03-29 23:32
Thank you, I will then stick with Jellyfin. Thanks.

**Comment by Fallenbagel** [comment] 2022-05-05 22:21
Plex login during setup now works in develop tag however, you cannot have two instances running together as in if you setup with jellyfin then you'll have to stick with jellyfin.

**Closed** 2022-05-08 12:08 UTC
