### ISSUE TITLE
[Feature Request] Users can opt-in to notificaations for other users' requests

### ISSUE THREAD

**Issue by ojmaster** [Fallenbagel/jellyseerr#560] opened 2023-11-11 01:58 UTC
### Description

When users have the `View Requests` permission, they can see other user's requests but I think it would be very nice to give them a button that allows them to opt-in for notifications (Ping multiple users for Discord, Email list for email notifs), this would mostly be useful because many users want to know when the newest season of a show is available. But it also is useful for Movie notifications aswell.

### Desired Behavior

In the Requests tab, there should be a button (Bell icon?) that allows you to opt-in to notifications for that request. This would also be useful to have in the Movie/Show's page.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2023-11-11 05:46
sct/overseerr#789

**Comment by ojmaster** [comment] 2023-11-20 04:10
@Fallenbagel it's a dead thread I was wondering if it could be implemented in Jellyseerr

**Comment by Fallenbagel** [comment] 2024-05-23 11:32
Duplicate of #375

**Closed** 2024-05-23 11:32 UTC
