### ISSUE TITLE
Possibility to "subscribe" to existing requests by other users

### ISSUE THREAD

**Issue by alvitali** [Fallenbagel/jellyseerr#937] opened 2024-08-18 23:00 UTC
### Description

Add the option for third users to "subscribe" to existing requests, in order to get notified about the availability. Most of my users use Jellyseerr's email notifications to get informed when an upcoming movie is available - however, if another user already requested it, they miss being notified.

### Desired Behavior

User has the option to "Also request" or "Subscribe" to an existing request by another user. This perhaps adds the movie to their profile and gives them notifications regarding its availability.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-08-19 00:21
Duplicate of #696

**Closed by Fallenbagel** 2024-08-19 00:21 UTC

**Comment by alvitali** [comment] 2024-08-24 23:16
> Duplicate of #696

I disagree, as the issue referenced is for a totally different request. The linked feature request wants to add another notifications provider to Jellyseerr, I'd like for some kind of logic implemented for multiple users to be notified about (yet) unavailable requests.

Do you implement features like this if they're added to Overseerr, or do you add your own features to Jellyseerr as well, seeing as Jellyseerr was forked from it?

**Comment by alvitali** [comment] 2024-08-24 23:21
Asking because this [feature request from overseerr](https://github.com/sct/overseerr/issues/789) does exactly what I'm looking for. You already pointed to that issue in #375, I just saw

**Comment by Fallenbagel** [comment] 2024-08-25 00:18
Sorry I meant to say #375

**Comment by Fallenbagel** [comment] 2024-08-25 00:21
> Do you implement features like this if they're added to Overseerr, or do you add your own features to Jellyseerr as well, seeing as Jellyseerr was forked from it?

We implement our own features. Jellyseerr can no longer pull features from overseerr as easily as it used to as we are on a different for a lack of a better word, "stack" than them given that jellyseerr now runs on nextjs 14, nodejs 20, pnpm, swc, and etc.
