### ISSUE TITLE
Add age ratings to filters

### ISSUE THREAD

**Issue by Ghissueguy** [Fallenbagel/jellyseerr#1114] opened 2024-11-21 20:46 UTC
### Description

One of the major hurdles I have with this software is the lack of ratings (G, PG,  PG-13, R, etc) in the filters for both movies and TV shows. 

### Desired Behavior

I would like an option to filter by applicable age ratings, making movies of interest easier to find by hiding all films/shows that do not have the selected rating. 

### Additional Context

A global option in the General settings to disable certain ratings for all users would also be welcome.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-11-22 07:14
Duplicate of #501

**Closed** 2024-11-22 07:15 UTC
Labels: enhancement, awaiting triage
