### ISSUE TITLE
Forward proxy support

### ISSUE THREAD

**Issue by Omripresent** [Fallenbagel/jellyseerr#1058] opened 2024-10-30 15:11 UTC
### Description

For air-gapped deployments (with no direct internet access) Jellyseerr should be able to make external requests using a forward proxy.
This functionality is in place for other *arr tools like Radarr, Sonarr, Lidarr, etc.

### Desired Behavior

External traffic should be able to use the http_proxy, https_proxy, no_proxy env vars or have a settings option similar to Radarr/Sonarr to define forward proxy settings.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment] 2024-10-30 15:14
Duplicate of #1025

**Closed by gauthier-th** 2024-10-30 15:14 UTC
Labels: enhancement, awaiting triage
