### ISSUE TITLE
Readarr support

### ISSUE THREAD

**Issue by binarygeek119** [Fallenbagel/jellyseerr#642] opened 2024-01-30 03:59 UTC
### Description

Readarr is a sonarr made for audiobooks and eBooks.

### Desired Behavior

Right now readarr is setup to do ether audiobooks or eBooks but not both.
Ideally it would make sense to support up to two readarrs. That way when some on ask for harry potter the get both a eBook and audiobook.
During the request you could have a box for eBook and/or audiobook.
I would also like ask for both by default 

### Additional Context

There's a new eBook metadata being worked on right now called bookbrainz
https://bookbrainz.org/

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2024-05-23 11:17
Duplicate of #134

**Closed** 2024-05-23 11:17 UTC
