### ISSUE TITLE
Allow users to delete their own requested content

### ISSUE THREAD

**Issue by MedPlex98** [Fallenbagel/jellyseerr#818] opened 2024-06-15 21:29 UTC
### Description

If users currently request films or series that are being watched and request new content, only the admin can delete the content that has already been viewed.

If my friends have watched films, they currently create a problem message with the text "Delete" and I have to delete the films manually.

So if I were to go on holiday for 2 weeks, I would have to keep deleting my friends' films and series, otherwise the hard drive would fill up.

### Desired Behavior

When users request content, they should be given the option of deleting this content at a later date.

It would be useful to know whether the content is currently being watched by another person, which could be queried by Plex or Tautulli.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment] 2024-06-20 12:35
Sounds like a duplicate of #308

**Comment by Fallenbagel** [comment] 2024-06-20 15:21
Duplicate of #308

**Closed by Fallenbagel** 2024-06-20 15:21 UTC
