### ISSUE TITLE
[Feature Request] Emails notifications for recently added medias

### ISSUE THREAD

**Issue by StunBeta** [Fallenbagel/jellyseerr#330] opened 2023-02-15 11:15 UTC
### Description

Possibility to send recently added medias by email

### Desired Behavior

In user's email notifications settings panel, add the possibility to send email (daily, weekly or monthly) for recently added medias (like newsletter)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2023-02-15 13:20
You mean in addition to what they request?

**Comment by Killianbe** [comment] 2023-02-22 21:54
i think he want say a Newsletter ! and it's a good idea

**Comment by Fallenbagel** [comment] 2023-02-23 11:50
> i think he want say a Newsletter ! and it's a good idea

I have a sort of newsletter thing script that directly connects with jellyfin instead of jellyseerr. You'll need to connect it with jellyfin webhook plugin.

You can customise it to send the message hourly, weekly, or even monthly (s for seconds, m for minutes and h for hours)

https://github.com/Fallenbagel/webhook-consolidator

**Comment by Killianbe** [comment] 2023-02-23 12:16
Compatible emby ?

**Comment by Fallenbagel** [comment] 2023-02-23 12:18
> Compatible emby ? 

As long as emby lets you configure a webhook template then yes

**Comment by kxenox** [comment] 2023-02-24 10:17
I agree, it would be awesome to be able to send a Newsletter directly from jellyseer without the need to configure webhooks or scripts !

**Comment by Fallenbagel** [comment] 2023-03-13 00:46
Just a heads up to anyone using jellyfin, there's a Newsletter plugin now

[Jellyfin Newsletter Plugin](https://github.com/cph015/Jellyfin-Newsletter-Plugin)

**Comment by bonswouar** [comment] 2024-04-06 11:53
Both those project don't seem maintained much any more (at least not as much as Jellyseerr), would love to see this implemented still.
And this seems to be a duplicate of #167

**Comment by karldonteljames** [comment] 2024-04-08 08:56
I agree, Moving to Jellyseerr from Ombi and a news letter is something that is configurable.
I always found it handy seeing what had been added to my server overnight when I got to work and checked my emails.
Thanks.

**Comment by gauthier-th** [comment] 2024-12-30 14:02
Duplicate of #167

**Closed by gauthier-th** 2024-12-30 14:02 UTC
